name             'teknobase'
maintainer       'Will Fisher'
maintainer_email 'will@teknofire.net'
license          'all_rights'
description      'Installs/Configures base'
long_description 'Installs/Configures base'
version          '0.2.0'

depends 'chef-client'
depends 'ntp'
depends 'apt'
